---
title: "Gov 50 Final Project"
author: "Saffron Agrawal"
description: "Saffron's final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

Milestone 1:
I am interested in exploring data related to character representation on TV. Specifically, I am interested in how different underrepresented groups are displayed on TV and with what frequency. I would love to overlay this information with general attitudes to different identity groups over time to see how TV representation may or may not make a difference. I plan to find this data utilizing Google Data Sets.

Milestone 2: 
For the Gov 50 Final Project, my research question is: What is the relationship between movies passing the Bechdel test and their domestic grossing. The Bechdel test is conducted on movies as a metric of determining gender bias by evaluating the nature of conversations among women in the films and whether they revolve around men or stand independent. I plan to use a data set provided by FiveThirtyEight and inspired by the study "The Dollar-And-Cents Case Against Hollywood’s Exclusion of Women" [https://fivethirtyeight.com/features/the-dollar-and-cents-case-against-hollywoods-exclusion-of-women/]. The data set lists a number of movies, the binary of whether they pass the Bechdel test, and the movies' budget, in addition to variables like domestic grossing and international grossing. I plan to examine the correlation among some of these variables to find out either if whether a movie passes the Bechdel test impacts the domestic grossing. My explanatory variable could be whether a movie passes the Bechdel test and the outcome could be the domestic grossing. I hypothesize that  movies that pass the Bechdel test might have a lower domestic grossing that those that do not. I plan to examine some of these variables through scatter plots to look at correlation. I have yet to decide whether to limit the time frame of the data because there are currently 1795 rows. There is also a scenario in which I look at the potential increase in movies that pass the Bechdel test over time. 
